import dotenv from 'dotenv';

dotenv.config();

console.log('\n🔍 Email Configuration Diagnosis\n');
console.log('=' .repeat(50));

// Check if variables are set
console.log('\n1. Environment Variables:');
console.log('   EMAIL_USER:', process.env.EMAIL_USER || '❌ NOT SET');
console.log('   EMAIL_PASS:', process.env.EMAIL_PASS ? `✅ SET (${process.env.EMAIL_PASS.length} characters)` : '❌ NOT SET');
console.log('   NOTIFICATION_EMAIL:', process.env.NOTIFICATION_EMAIL || '❌ NOT SET');

// Check for common issues
console.log('\n2. Common Issues Check:');

const issues = [];

// Check if EMAIL_USER is valid Gmail
if (process.env.EMAIL_USER) {
  if (!process.env.EMAIL_USER.endsWith('@gmail.com')) {
    issues.push('❌ EMAIL_USER must be a Gmail address (@gmail.com)');
  } else {
    console.log('   ✅ EMAIL_USER is a Gmail address');
  }
} else {
  issues.push('❌ EMAIL_USER is not set');
}

// Check if EMAIL_PASS has spaces
if (process.env.EMAIL_PASS) {
  if (process.env.EMAIL_PASS.includes(' ')) {
    issues.push('❌ EMAIL_PASS contains spaces - remove all spaces!');
  } else {
    console.log('   ✅ EMAIL_PASS has no spaces');
  }
  
  // Check password length (App passwords are 16 characters)
  if (process.env.EMAIL_PASS.length !== 16) {
    issues.push(`⚠️  EMAIL_PASS is ${process.env.EMAIL_PASS.length} characters (App passwords are usually 16)`);
  } else {
    console.log('   ✅ EMAIL_PASS is 16 characters (correct length)');
  }
} else {
  issues.push('❌ EMAIL_PASS is not set');
}

// Check if EMAIL_USER matches NOTIFICATION_EMAIL
if (process.env.EMAIL_USER && process.env.NOTIFICATION_EMAIL) {
  if (process.env.EMAIL_USER !== process.env.NOTIFICATION_EMAIL) {
    console.log('   ⚠️  EMAIL_USER and NOTIFICATION_EMAIL are different');
    console.log(`      Emails will be sent FROM: ${process.env.EMAIL_USER}`);
    console.log(`      Notifications will go TO: ${process.env.NOTIFICATION_EMAIL}`);
  } else {
    console.log('   ✅ EMAIL_USER matches NOTIFICATION_EMAIL');
  }
}

// Display issues
if (issues.length > 0) {
  console.log('\n3. Issues Found:');
  issues.forEach(issue => console.log('   ' + issue));
} else {
  console.log('\n3. ✅ No obvious configuration issues found');
}

// Provide solutions
console.log('\n4. Solutions:');
console.log('   ' + '─'.repeat(48));

if (process.env.EMAIL_USER === 'sontakkevarad@gmail.com') {
  console.log('\n   ⚠️  Your EMAIL_USER is: sontakkevarad@gmail.com');
  console.log('   ⚠️  But NOTIFICATION_EMAIL is: sontakkevarad210@gmail.com');
  console.log('\n   Question: Which Gmail account do you want to use?');
  console.log('   Option A: Use sontakkevarad@gmail.com');
  console.log('   Option B: Use sontakkevarad210@gmail.com');
  console.log('\n   If using Option B, update .env:');
  console.log('   EMAIL_USER=sontakkevarad210@gmail.com');
}

console.log('\n   📝 To fix "Invalid login" error:');
console.log('   1. Go to: https://myaccount.google.com/apppasswords');
console.log('   2. Sign in with the Gmail account you want to use');
console.log('   3. If you see "App passwords", click it');
console.log('   4. If you DON\'T see it, enable 2FA first:');
console.log('      https://myaccount.google.com/security');
console.log('   5. Generate new App Password:');
console.log('      - Select app: Mail');
console.log('      - Select device: Other (VaradBuilds)');
console.log('      - Click Generate');
console.log('   6. Copy the 16-character password (no spaces!)');
console.log('   7. Update EMAIL_PASS in server/.env');
console.log('   8. Restart server and test again');

console.log('\n   🧪 After updating .env, test with:');
console.log('   node server/test-email.js');

console.log('\n' + '='.repeat(50));
console.log('\n💡 Tip: The App Password is different from your Gmail password!');
console.log('   It\'s a special 16-character code generated by Google.\n');
